library(leaflet)
library(maps)
library(mapproj)
library(maptools)
library(RColorBrewer)
library(shiny)
library(shinyjs)
library(shinythemes)
library(rgdal)
library(sp)
library(raster)
library(mapview)
library(automap)
library(dygraphs)  ## new addition on 09/05/2017
library(xts)
library(plotly)
library(lubridate)
